/**
 * Action types aligned with the permission catalog architecture.
 */
export enum Action {
  CREATE = 'CREATE',
  DELETE = 'DELETE',
  DISABLE = 'DISABLE',
  ENABLE = 'ENABLE',
  RECOVER = 'RECOVER',
  TRANSFER_OWNERSHIP = 'TRANSFER_OWNERSHIP',
  VIEW = 'VIEW',
  UPDATE = 'UPDATE',

  ROTATE_TOKEN = 'ROTATE_TOKEN',
  GENERATE = 'GENERATE',
  PREVIEW = 'PREVIEW',

  CANCEL = 'CANCEL',
  CHECK_IN = 'CHECK_IN',
  COMPLETE = 'COMPLETE',
  REOPEN = 'REOPEN',
  RESET = 'RESET',
  START = 'START',
  UNDO_CANCEL = 'UNDO_CANCEL',
  UNDO_CHECK_IN = 'UNDO_CHECK_IN',
  UNSTART = 'UNSTART',

  ASSIGN = 'ASSIGN',
  UPDATE_STATUS = 'UPDATE_STATUS',
  UPDATE_SCHEDULE = 'UPDATE_SCHEDULE',
  CORRECT_TIMESTAMPS = 'CORRECT_TIMESTAMPS',
  UPDATE_TYPE = 'UPDATE_TYPE',

  SEARCH = 'SEARCH',
  ASSIGN_ROLES = 'ASSIGN_ROLES',
  INVITE = 'INVITE',
  REMOVE = 'REMOVE',
  UPLOAD = 'UPLOAD',
}
