/**
 * Action types for operations.
 *
 * The GraphQL schema's ActionType enum is intentionally not treated as the
 * source of truth here. This package keeps a richer application-level action
 * vocabulary for authorization, audit logging, and UI labels.
 */
export enum Action {
  CREATE = 'CREATE',
  READ = 'READ',
  DELETE = 'DELETE',
  RETRIEVE = 'RETRIEVE',
  UPDATE = 'UPDATE',
  PUT = 'PUT',
  LIST = 'LIST',

  MANAGE = 'MANAGE',
  VIEW = 'VIEW',
  SEARCH = 'SEARCH',

  GRANT = 'GRANT',
  REVOKE = 'REVOKE',

  PRESCRIBE = 'PRESCRIBE',
  DIAGNOSE = 'DIAGNOSE',
  SCHEDULE = 'SCHEDULE',
  CANCEL = 'CANCEL',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  SIGN = 'SIGN',
  VERIFY = 'VERIFY',

  RECOVER = 'RECOVER',
  DISABLE = 'DISABLE',

  SET_MEDICAL_SERVICE_STATUS = 'SET_MEDICAL_SERVICE_STATUS',
  SET_MEDICAL_SERVICE_FEES = 'SET_MEDICAL_SERVICE_FEES',
  CHECK_IN = 'CHECK_IN',
  UNDO_CHECK_IN = 'UNDO_CHECK_IN',
  START_SERVICE = 'START_SERVICE',
  UNSTART_SERVICE = 'UNSTART_SERVICE',
  COMPLETE_SERVICE = 'COMPLETE_SERVICE',
  REOPEN_COMPLETED_SERVICE = 'REOPEN_COMPLETED_SERVICE',
  CANCEL_SERVICE = 'CANCEL_SERVICE',
  UNDO_CANCEL_SERVICE = 'UNDO_CANCEL_SERVICE',
  FORCE_RESET_STATUS = 'FORCE_RESET_STATUS',
  CORRECT_TIMESTAMPS = 'CORRECT_TIMESTAMPS',

  UPDATE_STATUS = 'UPDATE_STATUS',
  VIEW_PATIENTS = 'VIEW_PATIENTS',
  PUT_PATIENT_PAYMENT = 'PUT_PATIENT_PAYMENT',
  DELETE_PATIENT_PAYMENT = 'DELETE_PATIENT_PAYMENT',

  EXPORT = 'EXPORT',
  IMPORT = 'IMPORT',
  ARCHIVE = 'ARCHIVE',
  RESTORE = 'RESTORE',
  SHARE = 'SHARE',
  DOWNLOAD = 'DOWNLOAD',
  UPLOAD = 'UPLOAD',

  ENABLE_CALENDAR_SYNC = 'ENABLE_CALENDAR_SYNC',
  DISABLE_CALENDAR_SYNC = 'DISABLE_CALENDAR_SYNC',
  REGENERATE_CALENDAR_LINK = 'REGENERATE_CALENDAR_LINK',

  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  CONFIGURE = 'CONFIGURE',
  AUDIT = 'AUDIT',
}
