/**
 * Resource types for operations
 */
export enum Resource {
  // Account & Ownership
  ACCOUNT = "ACCOUNT",
  ACCOUNT_OWNERSHIP = "ACCOUNT_OWNERSHIP",
  ACCOUNT_PREFERENCES = "ACCOUNT_PREFERENCES",

  // User & Contact
  USER = "USER",
  CONTACT = "CONTACT",

  // Patient resources
  PATIENT = "PATIENT",
  PATIENT_MEDICAL_NOTES = "PATIENT_MEDICAL_NOTES",
  PATIENT_MEDICAL_PROPERTIES = "PATIENT_MEDICAL_PROPERTIES",
  PATIENT_PUBLIC_PROPERTIES = "PATIENT_PUBLIC_PROPERTIES",
  PATIENT_PAYMENT = "PATIENT_PAYMENT",

  // Medical Service
  MEDICAL_SERVICE = "MEDICAL_SERVICE",
  MEDICAL_SERVICE_NOTE = "MEDICAL_SERVICE_NOTE",
  MEDICAL_SERVICE_SCHEDULE = "MEDICAL_SERVICE_SCHEDULE",
  MEDICAL_SERVICE_FEES = "MEDICAL_SERVICE_FEES",
  MEDICAL_SERVICE_STATUS = "MEDICAL_SERVICE_STATUS",

  // Medical resources
  MEDICAL_NOTE = "MEDICAL_NOTE",
  MEDICAL_RECORD = "MEDICAL_RECORD",
  MEDICAL_HISTORY = "MEDICAL_HISTORY",
  MEDICAL_HISTORY_MODEL = "MEDICAL_HISTORY_MODEL",
  PRESCRIPTION = "PRESCRIPTION",
  DIAGNOSIS = "DIAGNOSIS",
  OBSERVATION = "OBSERVATION",
  MEDICATION = "MEDICATION",
  ALLERGY = "ALLERGY",
  IMMUNIZATION = "IMMUNIZATION",
  PROCEDURE = "PROCEDURE",

  // Clinical & Measurements
  CLINICAL_NOTE = "CLINICAL_NOTE",
  VITAL_SIGNS = "VITAL_SIGNS",
  MEASURE_MODEL = "MEASURE_MODEL",
  CALCULATED_MEASURE_MODEL = "CALCULATED_MEASURE_MODEL",

  // Documents
  UPLOADED_DOCUMENT = "UPLOADED_DOCUMENT",
  DOCUMENT_LAYOUT = "DOCUMENT_LAYOUT",
  GENERATED_DOCUMENT = "GENERATED_DOCUMENT",
  DOCUMENT_MODEL = "DOCUMENT_MODEL",
  SNIPPET = "SNIPPET",

  // Appointments & Scheduling
  APPOINTMENT = "APPOINTMENT",
  LOCATION = "LOCATION",
  TASK_TYPE = "TASK_TYPE",

  // Diagnostic
  LAB_RESULT = "LAB_RESULT",
  IMAGING = "IMAGING",

  // Membership & Settings
  MEMBERSHIP = "MEMBERSHIP",
  SETTINGS = "SETTINGS",

  // System
  NOTIFICATION = "NOTIFICATION",
  REPORT = "REPORT",
  AUDIT_LOG = "AUDIT_LOG",
  SYSTEM = "SYSTEM",

  // Generic resources
  PUBLIC_RESOURCE = "PUBLIC_RESOURCE",
  MEDICAL_RESOURCE = "MEDICAL_RESOURCE",
}

/**
 * Medical resources - require special access control
 */
export const MEDICAL_RESOURCES: Resource[] = [
  Resource.PATIENT,
  Resource.PATIENT_MEDICAL_NOTES,
  Resource.PATIENT_MEDICAL_PROPERTIES,
  Resource.PATIENT_PAYMENT,
  Resource.MEDICAL_SERVICE,
  Resource.MEDICAL_SERVICE_NOTE,
  Resource.MEDICAL_SERVICE_SCHEDULE,
  Resource.MEDICAL_SERVICE_FEES,
  Resource.MEDICAL_SERVICE_STATUS,
  Resource.MEDICAL_NOTE,
  Resource.MEDICAL_RECORD,
  Resource.MEDICAL_HISTORY,
  Resource.MEDICAL_HISTORY_MODEL,
  Resource.PRESCRIPTION,
  Resource.DIAGNOSIS,
  Resource.OBSERVATION,
  Resource.MEDICATION,
  Resource.ALLERGY,
  Resource.IMMUNIZATION,
  Resource.PROCEDURE,
  Resource.CLINICAL_NOTE,
  Resource.VITAL_SIGNS,
  Resource.MEASURE_MODEL,
  Resource.CALCULATED_MEASURE_MODEL,
  Resource.LAB_RESULT,
  Resource.IMAGING,
  Resource.MEDICAL_RESOURCE,
];

/**
 * Public resources - standard access control
 */
export const PUBLIC_RESOURCES: Resource[] = [
  Resource.ACCOUNT,
  Resource.ACCOUNT_OWNERSHIP,
  Resource.ACCOUNT_PREFERENCES,
  Resource.USER,
  Resource.CONTACT,
  Resource.PATIENT_PUBLIC_PROPERTIES,
  Resource.UPLOADED_DOCUMENT,
  Resource.DOCUMENT_LAYOUT,
  Resource.GENERATED_DOCUMENT,
  Resource.DOCUMENT_MODEL,
  Resource.SNIPPET,
  Resource.APPOINTMENT,
  Resource.LOCATION,
  Resource.TASK_TYPE,
  Resource.MEMBERSHIP,
  Resource.SETTINGS,
  Resource.NOTIFICATION,
  Resource.REPORT,
  Resource.AUDIT_LOG,
  Resource.SYSTEM,
  Resource.PUBLIC_RESOURCE,
];

/**
 * Check if a resource is medical
 */
export function isMedicalResource(resource: Resource): boolean {
  return MEDICAL_RESOURCES.includes(resource);
}

/**
 * Check if a resource is public
 */
export function isPublicResource(resource: Resource): boolean {
  return PUBLIC_RESOURCES.includes(resource);
}
