/**
 * Resource types aligned with the GraphQL schema domain.
 */
export enum Resource {
  ACCOUNT = 'ACCOUNT',
  ACCOUNT_GENERAL_SETTINGS = 'ACCOUNT_GENERAL_SETTINGS',
  ACCOUNT_LOCATION = 'ACCOUNT_LOCATION',
  ACCOUNT_PREFERENCES = 'ACCOUNT_PREFERENCES',
  ACCOUNT_SUMMARY = 'ACCOUNT_SUMMARY',
  AVAILABLE_SLOT = 'AVAILABLE_SLOT',
  CALCULATED_MEASURE_MODEL = 'CALCULATED_MEASURE_MODEL',
  CALENDAR_SYNC = 'CALENDAR_SYNC',
  CALENDAR_TOKEN = 'CALENDAR_TOKEN',
  CONTACT = 'CONTACT',
  DOCUMENT_LAYOUT = 'DOCUMENT_LAYOUT',
  DOCUMENT_MODEL = 'DOCUMENT_MODEL',
  GENERATED_DOCUMENT = 'GENERATED_DOCUMENT',
  LOG_RECORD = 'LOG_RECORD',
  MEASURE_MODEL = 'MEASURE_MODEL',
  MEDICAL_HISTORY = 'MEDICAL_HISTORY',
  MEDICAL_HISTORY_MODEL = 'MEDICAL_HISTORY_MODEL',
  MEDICAL_SERVICE = 'MEDICAL_SERVICE',
  MEDICAL_SERVICE_ASSIGNEES = 'MEDICAL_SERVICE_ASSIGNEES',
  MEDICAL_SERVICE_DESCRIPTION = 'MEDICAL_SERVICE_DESCRIPTION',
  MEDICAL_SERVICE_FEES = 'MEDICAL_SERVICE_FEES',
  MEDICAL_SERVICE_LOCATION = 'MEDICAL_SERVICE_LOCATION',
  MEDICAL_SERVICE_NOTE = 'MEDICAL_SERVICE_NOTE',
  MEDICAL_SERVICE_SCHEDULE = 'MEDICAL_SERVICE_SCHEDULE',
  MEDICAL_SERVICE_STATUS = 'MEDICAL_SERVICE_STATUS',
  MEDICAL_SERVICE_TIMESTAMPS = 'MEDICAL_SERVICE_TIMESTAMPS',
  MEMBERSHIP = 'MEMBERSHIP',
  MEDICATION = 'MEDICATION',
  OBSERVATION = 'OBSERVATION',
  PATIENT = 'PATIENT',
  PATIENT_MEDICAL_NOTES = 'PATIENT_MEDICAL_NOTES',
  PATIENT_MEDICAL_PROPERTIES = 'PATIENT_MEDICAL_PROPERTIES',
  PATIENT_PAYMENT = 'PATIENT_PAYMENT',
  PATIENT_PROFILE = 'PATIENT_PROFILE',
  PATIENT_PUBLIC_PROPERTIES = 'PATIENT_PUBLIC_PROPERTIES',
  PATIENT_STATUS = 'PATIENT_STATUS',
  PRESCRIPTION = 'PRESCRIPTION',
  PRESCRIPTION_MODEL = 'PRESCRIPTION_MODEL',
  TASK_TYPE = 'TASK_TYPE',
  UPLOAD_DOCUMENT = 'UPLOAD_DOCUMENT',
  USER = 'USER',
  USER_CALENDAR_PREFERENCES = 'USER_CALENDAR_PREFERENCES',
  USER_PREFERENCES = 'USER_PREFERENCES',
}

const RESOURCE_CATEGORIES: {
  medical: Resource[];
  public: Resource[];
} = {
  medical: [
    Resource.AVAILABLE_SLOT,
    Resource.CALCULATED_MEASURE_MODEL,
    Resource.CONTACT,
    Resource.GENERATED_DOCUMENT,
    Resource.MEASURE_MODEL,
    Resource.MEDICAL_HISTORY,
    Resource.MEDICAL_HISTORY_MODEL,
    Resource.MEDICAL_SERVICE,
    Resource.MEDICAL_SERVICE_ASSIGNEES,
    Resource.MEDICAL_SERVICE_DESCRIPTION,
    Resource.MEDICAL_SERVICE_FEES,
    Resource.MEDICAL_SERVICE_LOCATION,
    Resource.MEDICAL_SERVICE_NOTE,
    Resource.MEDICAL_SERVICE_SCHEDULE,
    Resource.MEDICAL_SERVICE_STATUS,
    Resource.MEDICAL_SERVICE_TIMESTAMPS,
    Resource.MEDICATION,
    Resource.OBSERVATION,
    Resource.PATIENT,
    Resource.PATIENT_MEDICAL_NOTES,
    Resource.PATIENT_MEDICAL_PROPERTIES,
    Resource.PATIENT_PAYMENT,
    Resource.PATIENT_PROFILE,
    Resource.PATIENT_PUBLIC_PROPERTIES,
    Resource.PATIENT_STATUS,
    Resource.PRESCRIPTION,
    Resource.PRESCRIPTION_MODEL,
    Resource.UPLOAD_DOCUMENT,
  ],
  public: [
    Resource.ACCOUNT,
    Resource.ACCOUNT_GENERAL_SETTINGS,
    Resource.ACCOUNT_LOCATION,
    Resource.ACCOUNT_PREFERENCES,
    Resource.ACCOUNT_SUMMARY,
    Resource.CALENDAR_SYNC,
    Resource.CALENDAR_TOKEN,
    Resource.DOCUMENT_LAYOUT,
    Resource.DOCUMENT_MODEL,
    Resource.LOG_RECORD,
    Resource.MEMBERSHIP,
    Resource.TASK_TYPE,
    Resource.USER,
    Resource.USER_CALENDAR_PREFERENCES,
    Resource.USER_PREFERENCES,
  ],
} as const;

export const MEDICAL_RESOURCES: Resource[] = [...RESOURCE_CATEGORIES.medical];

export const PUBLIC_RESOURCES: Resource[] = [...RESOURCE_CATEGORIES.public];

export function isMedicalResource(resource: Resource): boolean {
  return RESOURCE_CATEGORIES.medical.indexOf(resource) !== -1;
}

export function isPublicResource(resource: Resource): boolean {
  return RESOURCE_CATEGORIES.public.indexOf(resource) !== -1;
}

export function getAllResources(): Resource[] {
  return [...RESOURCE_CATEGORIES.medical, ...RESOURCE_CATEGORIES.public];
}

export function getResourceCategories(): Readonly<typeof RESOURCE_CATEGORIES> {
  return RESOURCE_CATEGORIES;
}
